server.port: 8080

server.servlet.context-path: /springboot-mybatis

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-demo?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root

#数据库连接池配置
    hikari:
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      #不等于0且小于10秒，会被重置为10秒
      idle-timeout: 500000
      #连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
  #目的是为了省略resultType里的代码量，全路径名
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    #开启驼峰自动映射
#    map-underscore-to-camel-case: true
#    #延迟加载的全局开关，默认值false为不开启
#    lazy-loading-enabled: true


#分页插件
pagehelper:
  #指明数据库
  helper-dialect: mysql
  params: count=countSql
  #为true pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  supportMethodsArguments: false